### ISSUE TITLE
Some areas of the ending song subtitles cannot be refreshed

### ISSUE THREAD

**Issue by nyanmisaka** [Arcus92/libpgs-js#18]
![1](https://github.com/user-attachments/assets/6906e837-f46d-408f-8b8b-d3e7fd4728ff)

As shown in the picture, the area to the right of the subtitles underlined in red has not been refreshed, they are from an earlier timestamp. If I seek the video to the beginning at this time, these unrefreshed areas will also remain on the screen. This problem does not exist in FFmpeg.

The timestamp of the ending song of [this file](https://drive.google.com/file/d/1aSSoqchdLWyzrq43L_dmh7qCVFddA7QG/view?usp=sharing) starts at 01:24:57. Videos outside of the end credits have been censored.

**Comment by Arcus92** [comment]
Hi @nyanmisaka,
Thanks so much for this sample. It uses some PGS features I couldn't test before. 
The underlying issue was due to a misunderstanding of PGS windows.

**Comment by Arcus92** [comment]
Wasn't meant to end this message there...
The issue is now fix.
![grafik](https://github.com/user-attachments/assets/bdada6fb-e428-4c2b-b7a5-00576c69fee7)
I'll create a backport PR for Jellyfin 10.10.2.

**Comment by nyanmisaka** [comment]
Just tested it on my end and it works perfectly. Thanks for your quick response.
